# DATABASE
spring:
  mail:
    host: localhost
    port: 8125

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false
      hibernate:
        show_sql: false
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/data

app:
  base-url: ${APP_BASE_URL}

server:
  port: ${PORT:8081}

logging:
  level:
    org:
      hibernate:
        type: trace
