# DATABASE
spring:
  mail:
    host: localhost
    port: 8125

  datasource:
    url: jdbc:mysql://localhost:3308/template_bdd
    username: admin
    password: admin

  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false
      hibernate:
        show_sql: false
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/data

app:
  base-url: https://tanguylegoff.com

logging:
  level:
    org:
      hibernate:
        type: trace
