version: '3.8'
services:
  db:
    build:
      context: docker/timezoned-mysql
      args:
        MYSQL_VERSION: 9
    restart: always
    environment:
      TZ: Europe/Paris
      MYSQL_DATABASE: 'mindbloom_bdd'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:  # Ajout du healthcheck pour s'assurer que MySQL est prêt
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Paris
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    ports:
      - "8180:1080"
      - "8125:1025"

  swagger:
    build: 
      context: .  # Chemin vers le répertoire contenant le Dockerfile
      dockerfile: Dockerfile  # Assurez-vous que ce fichier existe
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    env_file:
      - ./.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db  # Doit correspondre au nom du service MySQL
      PMA_USER: admin
      PMA_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8082:80"  # Accès via http://localhost:8082


volumes:
  mysql-data:
