version: '3.3'
services:
  db:
    build:
      context: docker/timezoned-mysql
      args:
        MYSQL_VERSION: 9
    restart: always
    environment:
      TZ: Europe/Paris
      MYSQL_DATABASE: 'mindbloom_bdd'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Paris
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    ports:
      - "8180:1080"
      - "8125:1025"


volumes:
  mysql-data:
