// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/12/2024 14:33:36
const configMerger = require("C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/plugins/**/*.{js,ts,mjs}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/stores/**/*.{js,ts,mjs}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/composables/**/*.{js,ts,mjs}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/utils/**/*.{js,ts,mjs}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "C:/Users/antoi/Documents/Fac/M2/S9/MindBloom/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
